In [2]:
%load_ext autoreload
%autoreload 2

from math import sqrt, exp, log
from scipy.linalg import cholesky
import scipy as sp
import numpy as np
import numexpr as ne
import pandas as pd
from scipy.stats import random_correlation



In [3]:
import utils; print(utils)
from utils import *

<module 'utils' from '/home/ubuntu/aagit/aapackage/aapackage/control/utils.py'>


In [20]:
nasset = 2
nsimul=1
nstep= 5
T=5
s0  = np.ones((nasset))*100.0
vol0  = np.ones((nasset,1))*0.1
drift = 0.0
correl = np.identity(nasset) 

correl[1,0] = -0.99
correl[0,1] = -0.99




In [21]:
gbm_multi(nsimul, nasset, nstep, T, s0, vol0, drift, 
              correl, choice=0)
    


    

(2, 4, 1)


(array([[[100.        , 103.99317413,  98.59335647, 100.86429105,
           84.00963893],
         [100.        ,  99.4325715 , 100.12438865, 100.04249505,
          101.2110673 ]]]),
 array([[ 0.03925508, -0.05322138,  0.02287208, -0.18274442],
        [-0.00559044,  0.00703356, -0.00071825,  0.01171307]]),
 array([[ 0.39255078, -0.53221383,  0.2287208 , -1.82744419],
        [-0.05590445,  0.07033558, -0.00718253,  0.11713065]]),
 array([[ 1.        , -0.99      ],
        [ 0.        ,  0.14106736]]),
 array([[[ 2.17606395e-04],
         [-3.86040501e-02],
         [ 1.78314326e-01]],
 
        [[-3.96296131e-01],
         [ 4.98595736e-01],
         [-5.09156262e-02]]]))

In [7]:
np.dot( np.dot( vol0.T,  correl ), vol0 ) 

array([[0.0002]])

In [13]:
correl 

array([[ 1., -1.],
       [-1.,  1.]])